import { Component, computed, input } from '@angular/core';
import { CssUnitOrRawValue, resolveCssUnitOrRawValue } from '@ui-kit/types';

export const IconName = {
  AccountBalanceWallet: 'account_balance_wallet',
  AccountBalance: 'account_balance',
  Add: 'add',
  Analytics: 'analytics',
  Article: 'article',
  AvgTime: 'avg_time',
  Bar: 'bar',
  BarChart4: 'bar_chart_4',
  BarChart: 'bar_chart',
  Cached: 'cached',
  CalendarMonth: 'calendar_month',
  CandlestickChart: 'candlestick_chart',
  Category: 'category',
  CheckBoxOutlineBlank: 'check_box_outline_blank',
  CheckBox: 'check_box',
  Check: 'check',
  ChevronLeft: 'chevron_left',
  ChevronLineUp: 'chevron_line_up',
  CloseFullscreen: 'close_fullscreen',
  Close: 'close',
  CollapseContent: 'collapse_content',
  CreditCard: 'credit_card',
  CurrencyBitcoin: 'currency_bitcoin',
  CurrencyExchange: 'currency_exchange',
  DarkMode: 'dark_mode',
  Delete: 'delete',
  Dining: 'dining',
  Edit: 'edit',
  Enterprise: 'enterprise',
  ExpandContent: 'expand_content',
  FeaturedSeasonalAndGifts: 'featured_seasonal_and_gifts',
  FilterList: 'filter_list',
  Flag2: 'flag_2',
  Flag: 'flag',
  ForkChart: 'fork_chart',
  Grocery: 'grocery',
  History: 'history',
  HorizontalAlignCenter: 'horizontal_align_center',
  HourglassEmpty: 'hourglass_empty',
  Info: 'info',
  KeepOff: 'keep_off',
  Keep: 'keep',
  KeyboardArrowDown: 'keyboard_arrow_down',
  KeyboardArrowLeft: 'keyboard_arrow_left',
  KeyboardArrowRight: 'keyboard_arrow_right',
  KeyboardArrowUp: 'keyboard_arrow_up',
  KeyboardDoubleArrowDown: 'keyboard_double_arrow_down',
  KeyboardDoubleArrowLeft: 'keyboard_double_arrow_left',
  KeyboardDoubleArrowRight: 'keyboard_double_arrow_right',
  KeyboardDoubleArrowUp: 'keyboard_double_arrow_up',
  KidStar: 'kid_star',
  Leaderboard: 'leaderboard',
  LeftPanelClose: 'left_panel_close',
  LeftPanelOpen: 'left_panel_open',
  LightMode: 'light_mode',
  List: 'list',
  LocalFireDepartment: 'local_fire_department',
  Login: 'login',
  Logout: 'logout',
  Menu: 'menu',
  Mic: 'mic',
  MoneyBag: 'money_bag',
  MoneyOff: 'money_off',
  Monitoring: 'monitoring',
  Nutrition: 'nutrition',
  OpenInFull: 'open_in_full',
  OpenInNew: 'open_in_new',
  Paid: 'paid',
  PauseCircle: 'pause_circle',
  Pause: 'pause',
  PersonAdd: 'person_add',
  PhotoCamera: 'photo_camera',
  PlayArrow: 'play_arrow',
  PlayCircle: 'play_circle',
  PlayPause: 'play_pause',
  QuestionMark: 'question_mark',
  Refresh: 'refresh',
  Remove: 'remove',
  Replay: 'replay',
  Restaurant: 'restaurant',
  Savings: 'savings',
  Scale: 'scale',
  SelectCheckBox: 'select_check_box',
  Settings: 'settings',
  Signpost: 'signpost',
  Sort: 'sort',
  Star: 'star',
  StepInto: 'step_into',
  StopCircle: 'stop_circle',
  Stop: 'stop',
  SwapHoriz: 'swap_horiz',
  SyncDisabled: 'sync_disabled',
  Sync: 'sync',
  Timeline: 'timeline',
  Undo: 'undo',
  UnfoldLess: 'unfold_less',
  UnfoldMore: 'unfold_more',
  UniversalCurrencyAlt: 'universal_currency_alt',
  UniversalCurrency: 'universal_currency',
  Verified: 'verified',
  ViewCozy: 'view_cozy',
  VisibilityOff: 'visibility_off',
  Visibility: 'visibility',
  Warning: 'warning',
  WatchScreentime: 'watch_screentime',
  Whatshot: 'whatshot',
} as const;

export type IconName = (typeof IconName)[keyof typeof IconName];

@Component({
  selector: 'v-icon',
  templateUrl: './v-icon.html',
  styleUrl: './v-icon.css',
  host: {
    '[style.--v-icon-size]': 'iconUnitSizeString$$()',
    '[style.--v-icon-background]': 'iconBackgroundString$$()',
    '[style.--v-icon-color]': 'color()',
  },
})
export class VIcon {
  public readonly name = input.required<IconName>();
  public readonly size = input<CssUnitOrRawValue>(6);
  public readonly color = input<string>();

  public readonly iconBackgroundString$$ = computed(() => {
    return `url(ui-kit-assets/icons/${this.name()}.svg)`;
  });
  public readonly iconUnitSizeString$$ = computed(() => {
    return resolveCssUnitOrRawValue(this.size());
  });
}
